FROM gcr.io/kaggle-gpu-images/python:latest

RUN apt-get update &&\
    apt-get install -y zsh &&\
    apt-get clean

RUN python -m pip install --upgrade pip &&\
    bash -c "curl -sSL https://install.python-poetry.org | POETRY_HOME=/usr/local python - --yes --preview"

ENTRYPOINT [ "python" ]
