name: build_and_push_kaggle

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push python-kaggle image
        id: docker_build_python_cuda
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.kaggle
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-kaggle
