name: build_and_push

on:
  workflow_dispatch:
    inputs:
      py_version:
        description: 'python version'
        required: true
        default: 'latest'
      cuda_version:
        description: 'cuda version'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push python-cuda image
        id: docker_build_python_cuda
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.cuda
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-cuda:${{ github.event.inputs.py_version }}-${{ github.event.inputs.cuda_version }}
          build-args: |
            PYTHON_VERSION=${{ github.event.inputs.py_version }}
            CUDA_VERSION=${{ github.event.inputs.cuda_version }}
